---
title: "Prediction of Diabetes"
author: "Sridhar"
date: "August 8, 2018"
output: 
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

## Loading the required libraries
```{r}
library(ggplot2)
library(corrplot)
library(caTools)
library(ROCR)
```

## Load the data
The observations of the people are stored in a CSV format, named diabetes.csv.The data is loaded in the environment.Let's check how the data is structured.
```{r}
data = read.csv("diabetes.csv")
head(data)
```

## Correlations
```{r}

correlations <- cor(data)
corrplot(correlations, method="color")
```

## Visualizations
```{r}
pairs(data, col=data$Outcome)
```


## Preparing the data

```{r}
set.seed(88)
split <- sample.split(data$Outcome, SplitRatio = 0.75)
dresstrain <- subset(data, split == TRUE)
dresstest <- subset(data, split == FALSE)
```



## Logistic regression
```{r}
model <- glm (Outcome ~ .-Pregnancies + Glucose + BloodPressure + SkinThickness + Insulin + BMI + DiabetesPedigreeFunction + Age, data = dresstrain, family = binomial)
summary(model)
```

```{r}
predict_train <- predict(model, type = 'response')
predict_test <- predict(model, newdata = dresstest, type = 'response')

```

```{r}
table(dresstrain$Outcome, predict_train > 0.5)
```

```{r}

ROCRpred <- prediction(predict_train, dresstrain$Outcome)
ROCRperf <- performance(ROCRpred, 'tpr','fpr')
plot(ROCRperf, colorize = TRUE, text.adj = c(-0.2,1.7))

```


